version: 0.0
os: linux
files:
  - source: \
    destination: /home/ec2-user/springboot-webservice/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    gruop: ec2-user